Sto pick skill
navikt/crm-sto pull request #543
Opened 2023-12-13 13:27 UTC by mamikals

2024-01-05 15:56 UTC, EirikFladby requested changes
Nice :)
Dette løser kun første del av Jira-oppgaven though. Hva har dere blitt enig om rundt det å skru av skills for alle?

> Trafikk har til tider lyst å skru av Skills slik at andre skills blir prioritert. Dette er vanligvis knyttet til overtidsarbeid som er rettet mot å arbeide ned en kø med stor backlog.
> 
> De ønsker spesielt at de får kontroll av hvilke skills blir skrudd av og når det skjer.
> 
> Foreslått løsning: Lage et nytt objekt, Excluded Skills elns., med en checkbox active som trafikk kan redigere. Så lager vi et record for hver skill vi har, Helse, Pensjon etc. Så oppdaterer vi nksGetStoUtilityController.cls til å ikke hente de serviceResourceSkillsene.
> 
> Også et ønske fra statistikk at vi får reporting data på dette slik at de kan fremvise det i sine dashboards så det kan være public.

2024-01-05 15:56 UTC, EirikFladby commented on force-app/main/default/classes/nksGetStoUtilityController.cls
> +        }
Jeg syns dette ble litt rotete med én liste for skill og én for id for hver skilltype. Kan du ikke heller erstatte disse 6 listene med 3 maps med SkillId og DeveloperName?

2024-01-05 15:56 UTC, EirikFladby commented on force-app/main/default/classes/nksGetStoUtilityController.cls
> +    private static List<String> userOriginSkills = new List<String>();
Disse brukes ikke?

2024-01-11 08:31 UTC, mamikals commented
Trafikk mener det er dekkende nok å la veilederne velge selv, de trenger ikke en måte å disable skills så lenge de har det.

2024-01-15 08:50 UTC, EirikFladby approved these changes

2024-01-16 14:39 UTC, merged