Manage sto news
navikt/crm-sto pull request #549
Opened 2024-01-05 13:20 UTC by mamikals

2024-01-12 08:07 UTC, mamikals commented
Trenger litt hjelp med noen ekstra punkt også.

- Er FAQs et bra navn for dette objektet? Jeg syntes STO News ble litt knødd, det har jo lite med Nyheter å gjøre egentlig. Men kanskje CRM_FAQ__C er mer passende, uansett tar jeg imot forslag hehe.
- Jeg har satt FAQs til å være public read ekstern, er det kanskje bedre å sette sharing rules for det?
- Hvis vi bruker sharing rules, burde vi bare share FAQs som er "enabled"?

2024-01-15 08:40 UTC, EirikFladby requested changes
LWCen mangler her.
Må også legge til i permset for de som skal redigere FAQ-recordene internt, nå er det kun eksterne brukere som får tilgang i STO_Experience perm set.

2024-01-15 08:45 UTC, EirikFladby commented
> Trenger litt hjelp med noen ekstra punkt også.
> 
> * Er FAQs et bra navn for dette objektet? Jeg syntes STO News ble litt knødd, det har jo lite med Nyheter å gjøre egentlig. Men kanskje CRM_FAQ__C er mer passende, uansett tar jeg imot forslag hehe.
> * Jeg har satt FAQs til å være public read ekstern, er det kanskje bedre å sette sharing rules for det?
> * Hvis vi bruker sharing rules, burde vi bare share FAQs som er "enabled"?

- Jeg liker FAQ :) CRM_FAQ er også fint, vi liker jo å prepende namespaces :P
- Tenker at vi ikke trenger sharing set for Experience Cloud ettersom vi viser bare de som skal vises via en query via LWC, så det kan like så godt være private read/write imo. 
- Med mindre dette noensinne blir aktuelt for andre team å ta i bruk, så er public read/write internt greit, tenker jeg. Hvis andre team vil ta det i bruk på et tidspunkt er jo private read/write bedre så kan vi skille på det via sharing rule på domain elns.

2024-01-15 08:50 UTC, mamikals commented
Skal ikke ha LWC lenger 😄, vi går for standard Salesforce listView og Record page editing.
Permissionset er fair, det hadde jeg glømt litt av.
Trur jeg endrer det til CRM_FAQ da 😄, men vi burde unngå public read/write, siden bare kommunikasjon skal kunne redigere disse meldingene.

2024-01-15 09:13 UTC, EirikFladby commented
> Skal ikke ha LWC lenger 😄, vi går for standard Salesforce listView og Record page editing. Permissionset er fair, det hadde jeg glømt litt av. Trur jeg endrer det til CRM_FAQ da 😄, men vi burde unngå public read/write, siden bare kommunikasjon skal kunne redigere disse meldingene.

Ah, tenkte på LWC for Innboks, men dette er jo samme metode som brukes nå, good 😄 

Okei, hvis kun kommunikasjon skal ha tilgang så kan vi sette private og del alle recordene med kommunikasjon via sharing set da.

2024-01-15 12:54 UTC, mamikals commented
Jeg har godt for å gjøre det public read både eksternt og internt 😄, tenker det er ingenting galt i at folk kan få tak i FAQs som ikke er publisert egentlig. Det er jo ment som åpen informasjon da, men mulig vi må endre litt på sharing hvis andre team vil ta i bruk objektet.

2024-01-17 12:07 UTC, EirikFladby requested changes
Glemt CRM_Ordering__c i perm set

2024-01-17 12:07 UTC, EirikFladby commented on force-app/main/default/objectTranslations/CRM_FAQ__c-no/CRM_FAQ__c-no.objectTranslation-meta.xml
> +    </webLinks>
Woot? 🤣

2024-01-17 12:07 UTC, EirikFladby commented on force-app/main/default/classes/stoHelperClass.cls
> +            ORDER BY CRM_Ordering__c DESC
Er det ikke mer intuitivt om det er ASC? Slik at 1 er høyeste prio aka på toppen?

2024-01-19 10:09 UTC, mamikals commented on force-app/main/default/objectTranslations/CRM_FAQ__c-no/CRM_FAQ__c-no.objectTranslation-meta.xml
> +    </webLinks>
Fair fair, koselig kar han

2024-01-19 10:10 UTC, mamikals commented on force-app/main/default/classes/stoHelperClass.cls
> +            ORDER BY CRM_Ordering__c DESC
Tja kanskje, jeg tenkte det mer en z-index så du alltid kan gi noe høyere prioritet enn de andre. Du bryr deg sjeldent om hva som er på bunnen tenker jeg

2024-01-19 10:16 UTC, mamikals commented on force-app/main/default/classes/stoHelperClass.cls
> +            ORDER BY CRM_Ordering__c DESC
Hørte med Sara og hun var enig med deg om ASC 😄

2024-01-19 10:18 UTC, EirikFladby approved these changes

2024-01-22 09:15 UTC, merged