Expanded timeline
navikt/crm-sto pull request #715
Opened 2024-12-20 07:42 UTC by mamikals

2024-12-23 11:23 UTC, vegarduri requested changes

2024-12-23 11:23 UTC, vegarduri commented on force-app/main/default/lwc/threadExpandedTimeline/threadExpandedTimeline.html
> +    <section role="log" class="slds-theme_default" style="border-bottom: 1px solid black; padding-bottom: 1.5rem">
Bedre å ha style i CSS?

2024-12-23 11:23 UTC, vegarduri commented on force-app/main/default/lwc/threadExpandedTimeline/threadExpandedTimeline.html
> +    <div style="padding-bottom: 1rem; padding-top: 1.5rem">
samme her

2024-12-23 11:23 UTC, vegarduri commented on force-app/main/default/lwc/threadExpandedTimeline/threadExpandedTimeline.js
> +        // if (this.logEvent) {
Skal dette være med?

2025-01-07 14:24 UTC, EirikFladby requested changes

2025-01-07 14:24 UTC, EirikFladby commented on force-app/main/default/lwc/threadExpandedTimeline/threadExpandedTimeline.js
> +    @track messages;
Du trenger ikke track her ettersom du reassigner verdiene til formattedMessages uansett. Da blir reactivity håndtert av LWC. Dvs. at du kan også fjerne formattedMessages.

2025-01-17 13:04 UTC, EirikFladby approved these changes

2025-01-17 13:08 UTC, vegarduri approved these changes

2025-01-17 13:08 UTC, merged